name = "fire-drill-test"
main = "workers-site/index.js"
compatibility_date = "2024-01-15"

[site]
bucket = "./dist"

[[r2_buckets]]
binding = "FIRE_DRILL_PROJECTS"
bucket_name = "fire-drill-projects"
