name = "fire-drill"
main = "workers-site/index.js"
compatibility_date = "2023-12-01"

# Import local configuration for development
# Use: wrangler dev --config config.local.toml
# For production, use environment variables or secrets

# Variables for development - Use environment variables or secrets for production
[vars]
# GOOGLE_CLIENT_ID = "your-google-client-id"
# GOOGLE_CLIENT_SECRET = "your-google-client-secret"

[[d1_databases]]
binding = "DB"
database_name = "fire-drill-db"
database_id = "ca36eabc-2859-411c-99b1-653f6fc2ba56"
