name = "fire-drill-test"
main = "workers-site/index.js"
compatibility_date = "2023-12-01"

[[d1_databases]]
binding = "DB"
database_name = "fire-drill-db"
database_id = "ca36eabc-2859-411c-99b1-653f6fc2ba56"
